In [2]:
import numpy as np

In [34]:
a = np.arange(120).reshape(3,4,10)
a + np.ones(120).reshape(3, 4, 10)

array([[[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
        [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.]],

       [[ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
        [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
        [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.]],

       [[ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
        [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.],
        [101., 102., 103., 104., 105., 106., 107., 108., 109., 110.],
        [111., 112., 113., 114., 115., 116., 117., 118., 119., 120.]]])

In [35]:
a + 1

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
        [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115, 116, 117, 118, 119, 120]]])

### Broadcasting은 3가지 동작으로 진행됩니다.

#### 1. padding - 고차원 방향으로만 진행이 된다.
#### 2. copy - 차원 1인 것을 해당 차원에 맞게 확장해서 연산한다.
#### 3. operation - 연산한다.

# [NumPy 연습 문제]

In [36]:
import numpy as np

#### 연습문제 1. 배열 재형성하기
아래 arr 배열을 4x5 행렬로 변환하세요.

In [37]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr.reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### 연습문제 2. 배열 재형성하기 
5x4 shape을 가진 배열 선언 후, 1차원으로 변환하세요

In [40]:
arr = np.arange(20).reshape(5, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 연습문제 3. 배열 이어붙이기

아래 3개 배열을 1차원으로 결합하세요. 
- x : [1, 2, 3]
- y : [3, 2, 1]
- z : [99, 99]

In [43]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([99,99])

In [44]:
np.hstack([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99])

In [49]:
np.concatenate([x,y,z], axis=0)

array([ 1,  2,  3,  3,  2,  1, 99, 99])

아래 2차원 2개 배열을 첫번째 축을 따라 연결하세요
- x : [[1, 2, 3], [4, 5, 6]]
- y : [[1, 1, 1], [2, 2, 2]]

In [50]:
x = np.array([[1,2,3],
              [4,5,6]])
y = np.array([[1,1,1],
              [2,2,2]])

In [57]:
x.shape

(2, 3)

In [58]:
y.shape

(2, 3)

In [53]:
np.concatenate([x, y], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [54]:
np.vstack([x, y])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

아래 2차원 2개 배열을 두번째 축을 따라 연결하세요
- x : [[1, 2, 3], [4, 5, 6]]
- y : [[1, 1, 1], [2, 2, 2]]

In [65]:
np.hstack([x, y]).reshape(2, -1, 6)

array([[[1, 2, 3, 1, 1, 1]],

       [[4, 5, 6, 2, 2, 2]]])

#### 연습문제 4. 브로드 캐스팅
아래 10x3 배열을 중앙 정렬하세요. (X - X_mean)
- X : (10x3) shape을 가진 matrix
- X_mean : 각 열의 평균값 (3, )

In [66]:
X = np.arange(30).reshape((10,3))
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [67]:
X.shape

(10, 3)

In [71]:
X_mean = X.mean(axis=1)

In [72]:
X_mean

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28.])

In [73]:
X - X_mean

ValueError: operands could not be broadcast together with shapes (10,3) (10,) 